<?php
    $films = [
        [
            'title' => 'Avatar',
            'director' => 'James Cameron',
            'year' => 2009,
            'poster' => 'https://pad.mymovies.it/filmclub/2008/03/090/imm.jpg',
            'genre' => 'Sci-fi/Azione',
            'duration' => '2.40h',
        ],
        [
            'title' => 'Yes Man',
            'director' => 'Peyton Reed',
            'year' => 2008,
            'poster' => 'https://pad.mymovies.it/filmclub/2008/07/090/immpg5.jpg',
            'genre' => 'Commedia/Romantico',
            'duration' => '1.44h',
        ],
        [
            'title' => 'IT',
            'director' => 'Tommy Lee Wallace',
            'year' => 1993,
            'poster' => 'https://ae01.alicdn.com/kf/HTB14AOcbBWD3KVjSZFsq6AqkpXaG/Q1349-Poster-e-stampe-IT-Movie-Pennywise-1990-Classic-Film-Art-Poster-Canvas-Painting-Home-Decor.jpg',
            'genre' => 'Horror/Thriller',
            'duration' => '3.12h',
        ],
        [
            'title' => 'Ritorno Al Futuro',
            'director' => 'Robert Zemeckis',
            'year' => 1985 ,
            'poster' => 'https://aforismi.meglio.it/img/film/ritorno-al-futuro.jpg',
            'genre' => ' Sci-fi/Commedia',
            'duration' => '1.56h',
        ],
        [
            'title' => 'Dune',
            'director' => 'Denis Villeneuve',
            'year' => 2021,
            'poster' => 'https://aforismi.meglio.it/img/film/Dune-2021.jpg',
            'genre' => 'Sci-fi/Avventura',
            'duration' => '2.35h',
        ],
        [
            'title' => 'Sport contro voglia',
            'director' => 'Lucio Ghedina',
            'year' => 2013,
            'poster' => 'https://i.ytimg.com/vi/bhGUDbm_670/maxresdefault.jpg',
            'genre' => 'Sport',
            'duration' => '0.10h',
        ],
        [
            'title' => 'Il Grande Gatsby',
            'director' => 'Baz Luhrmann',
            'year' => 2013,
            'poster' => 'https://pad.mymovies.it/filmclub/2010/11/083/locandina.jpg',
            'genre' => 'Romantico/Drammatico',
            'duration' => '2.22h',
        ],
        [
            'title' => 'Inception',
            'director' => 'Christopher Nolan',
            'year' => 2010 ,
            'poster' => 'https://m.media-amazon.com/images/I/91Rc8cAmnAL._AC_SY679_.jpg',
            'genre' => 'Azione/Sci-fi',
            'duration' => '2.28h',
        ],
        [
            'title' => 'Interstellar',
            'director' => 'Christopher Nolan',
            'year' => 2014,
            'poster' => 'https://m.media-amazon.com/images/I/51nh4mBNzaL._AC_.jpg',
            'genre' => 'Sci-fi/Avventura',
            'duration' => '2.49h',
        ],
        [
            'title' => 'Avengers: Endgame',
            'director' => 'Anthony Russo, Joe Russo',
            'year' => 2019,
            'poster' => 'https://static.posters.cz/image/1300/poster/avengers-endgame-journey-s-end-i122136.jpg',
            'genre' => 'Azione/Sci-fi',
            'duration' => '3.02h',
        ]
    ];

?>